# Generated by Django 3.0.5 on 2021-03-14 01:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subpages', '0002_confessions_examcorner_machinelearning_webdevelopment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machinelearning',
            new_name='ml',
        ),
    ]
